--liquibase formatted sql

--changeset academia:01-create-users-table
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(20) NOT NULL PRIMARY KEY,
    user_type VARCHAR(31) NOT NULL,
    password VARCHAR(255),
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    email VARCHAR(100),
    description VARCHAR(4000),
    student_name VARCHAR(50),
    gender VARCHAR(30),
    date_of_birth VARCHAR(50),
    major VARCHAR(50),
    department VARCHAR(50),
    cohort VARCHAR(50),
    academic_advior VARCHAR(50),
    teacher_name VARCHAR(50),
    employee_id VARCHAR(30),
    designation VARCHAR(50),
    specialization VARCHAR(50)
);

--changeset academia:01-create-authorities-table
CREATE TABLE IF NOT EXISTS authorities (
    users_username VARCHAR(20) NOT NULL,
    authorities VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (users_username) REFERENCES users(username)
);

--changeset academia:01-create-course-table
CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    code VARCHAR(50),
    name VARCHAR(255),
    credit INT,
    description VARCHAR(255),
    reference VARCHAR(255)
);

--changeset academia:01-create-user-course-table
CREATE TABLE IF NOT EXISTS user_course (
    username VARCHAR(20) NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT fk_user_course_users FOREIGN KEY (username) REFERENCES users(username),
    CONSTRAINT fk_user_course_course FOREIGN KEY (course_id) REFERENCES course(id)
);

--changeset academia:01-create-files-table
CREATE TABLE IF NOT EXISTS files (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    file_name VARCHAR(255),
    file_type VARCHAR(100),
    url VARCHAR(255),
    data BYTEA,
    username VARCHAR(20) NOT NULL,
    CONSTRAINT fk_files_users FOREIGN KEY (username) REFERENCES users(username)
);

--changeset academia:01-create-password-reset-token-table
CREATE TABLE IF NOT EXISTS password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    token VARCHAR(255),
    expiry_date TIMESTAMP,
    user_id VARCHAR(20),
    CONSTRAINT fk_password_reset_token_users FOREIGN KEY (user_id) REFERENCES users(username)
);

--changeset academia:01-create-academic-tables
CREATE TABLE IF NOT EXISTS school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    class_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    section_name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS class_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    class_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    class_teacher_username VARCHAR(20),
    class_captain_username VARCHAR(20),
    sports_captain_username VARCHAR(20),
    CONSTRAINT fk_class_sections_class FOREIGN KEY (class_id) REFERENCES school_classes(id),
    CONSTRAINT fk_class_sections_section FOREIGN KEY (section_id) REFERENCES sections(id),
    CONSTRAINT fk_class_sections_teacher FOREIGN KEY (class_teacher_username) REFERENCES users(username),
    CONSTRAINT fk_class_sections_captain FOREIGN KEY (class_captain_username) REFERENCES users(username),
    CONSTRAINT fk_class_sections_sports_captain FOREIGN KEY (sports_captain_username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS school_calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_date DATE NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    type VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS timetable_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    class_section_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    teacher_username VARCHAR(20) NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    period_number INT NOT NULL,
    start_time VARCHAR(10),
    end_time VARCHAR(10),
    CONSTRAINT fk_timetable_slots_class_section FOREIGN KEY (class_section_id) REFERENCES class_sections(id),
    CONSTRAINT fk_timetable_slots_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT fk_timetable_slots_teacher FOREIGN KEY (teacher_username) REFERENCES users(username)
);
