--liquibase formatted sql

--changeset academia:05-create-student-enrollments-table
CREATE TABLE IF NOT EXISTS student_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    student_username VARCHAR(20) NOT NULL,
    class_section_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    roll_number VARCHAR(30),
    status VARCHAR(20) DEFAULT 'ENROLLED' NOT NULL,
    enrolled_at TIMESTAMP,
    CONSTRAINT fk_student_enrollments_student FOREIGN KEY (student_username) REFERENCES users(username),
    CONSTRAINT fk_student_enrollments_class_section FOREIGN KEY (class_section_id) REFERENCES class_sections(id),
    CONSTRAINT fk_student_enrollments_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id)
);
