--liquibase formatted sql

--changeset academia:06-create-activities-table
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(30) NOT NULL,
    academic_year_id BIGINT,
    event_date DATE NOT NULL,
    registration_deadline DATE,
    venue VARCHAR(100),
    status VARCHAR(25) DEFAULT 'PLANNING' NOT NULL,
    coordinator_username VARCHAR(20),
    CONSTRAINT fk_activities_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
    CONSTRAINT fk_activities_coordinator FOREIGN KEY (coordinator_username) REFERENCES users(username)
);

--changeset academia:06-create-activity-participants-table
CREATE TABLE IF NOT EXISTS activity_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    student_username VARCHAR(20) NOT NULL,
    role VARCHAR(50) DEFAULT 'Participant',
    team_name VARCHAR(100),
    position VARCHAR(50),
    remarks VARCHAR(250),
    registered_at TIMESTAMP,
    CONSTRAINT fk_activity_participants_activity FOREIGN KEY (activity_id) REFERENCES activities(id),
    CONSTRAINT fk_activity_participants_student FOREIGN KEY (student_username) REFERENCES users(username)
);

--changeset academia:06-create-activity-results-table
CREATE TABLE IF NOT EXISTS activity_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    event_name VARCHAR(100) NOT NULL,
    winner_name VARCHAR(100) NOT NULL,
    winner_class VARCHAR(50),
    position VARCHAR(50) NOT NULL,
    score VARCHAR(50),
    CONSTRAINT fk_activity_results_activity FOREIGN KEY (activity_id) REFERENCES activities(id)
);
