--liquibase formatted sql

--changeset academia:04-create-academic-years-table
CREATE TABLE IF NOT EXISTS academic_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'PLANNING' NOT NULL,
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_by VARCHAR(20),
    CONSTRAINT fk_academic_years_created_by FOREIGN KEY (created_by) REFERENCES users(username)
);

--changeset academia:04-seed-default-academic-year
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM academic_years
INSERT INTO academic_years (name, start_date, end_date, status, created_at)
VALUES ('2026-2027', '2026-04-01', '2027-03-31', 'ACTIVE', '2026-04-01 00:00:00');

--changeset academia:04-add-academic-year-fk-to-class-sections
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.table_constraints WHERE lower(constraint_name) = 'fk_class_sections_academic_year'
ALTER TABLE class_sections ADD COLUMN IF NOT EXISTS academic_year_id BIGINT DEFAULT 1;
ALTER TABLE class_sections ADD CONSTRAINT fk_class_sections_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);

--changeset academia:04-add-academic-year-fk-to-timetable-slots
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.table_constraints WHERE lower(constraint_name) = 'fk_timetable_slots_academic_year'
ALTER TABLE timetable_slots ADD COLUMN IF NOT EXISTS academic_year_id BIGINT DEFAULT 1;
ALTER TABLE timetable_slots ADD CONSTRAINT fk_timetable_slots_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);

--changeset academia:04-add-academic-year-fk-to-calendar-events
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.table_constraints WHERE lower(constraint_name) = 'fk_calendar_events_academic_year'
ALTER TABLE school_calendar_events ADD COLUMN IF NOT EXISTS academic_year_id BIGINT DEFAULT 1;
ALTER TABLE school_calendar_events ADD CONSTRAINT fk_calendar_events_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
